### ISSUE TITLE
NoClassDefFoundError during NoPadding encryption

### ISSUE THREAD

**Issue by thekia19** [Richard-W/scalacrypt#5] opened 2019-03-07 10:13 UTC
Hello guys, 

thank you very much for you library.
I would like to continue using it but encountered with an issue. Please consider an error by the link to Scastie: https://scastie.scala-lang.org/rXvywX7RQ42LqDb7OaMjxw

just for not loosing it I'll duplicate everything from Scastie below:
There is a method:
```
def generateAccessToken(input: String,
                        keyStr: String,
                        iv: String): Option[String] = {
  import xyz.wiedenhoeft.scalacrypt._
  def repeatChar(c: Char, n: Int): String = c.toString * n
  //s + (bs - len(s) % bs) * chr(bs - len(s) % bs)
  val blockSize = 16
  val encoding  = "UTF-8"
  val padded    = input +
    repeatChar((blockSize - input.length % blockSize).toChar, blockSize - input.length % blockSize)
  val keyTry    = keyStr.getBytes(encoding).toSeq.toKey[SymmetricKey128].toOption
  for {
    key   <- keyTry
    suite <- suites.AES128_CBC_NoPadding(key, Option(iv.getBytes(encoding))).toOption
    enc   <- suite.encrypt(padded.getBytes(encoding).toSeq).toOption
  } yield enc.toString
}
```

during the suite.encrypt runtime error occurs:
```
Uncaught error from thread [application-akka.actor.default-dispatcher-156]: scala/collection/TraversableOnce$class, shutting down ActorSystem[application]
java.lang.NoClassDefFoundError: scala/collection/TraversableOnce$class
	at xyz.wiedenhoeft.scalacrypt.BlockCipherSuite$$anon$1.<init>(BlockCipherSuite.scala:47)
	at xyz.wiedenhoeft.scalacrypt.BlockCipherSuite.encrypt(BlockCipherSuite.scala:47)
	at xyz.wiedenhoeft.scalacrypt.BlockCipherSuite.encrypt(BlockCipherSuite.scala:43)
	at widgets.analytics_v1.AnalyticsActions$.$anonfun$generateAccessToken$2(AnalyticsActions.scala:86)
	at scala.Option.flatMap(Option.scala:171)
	at widgets.analytics_v1.AnalyticsActions$.$anonfun$generateAccessToken$1(AnalyticsActions.scala:85)
	at scala.Option.flatMap(Option.scala:171)
	at widgets.analytics_v1.AnalyticsActions$.generateAccessToken(AnalyticsActions.scala:84)
	at widgets.analytics_v1.AnalyticsActions$.$anonfun$resolveMggTrackerConfigGeneric$6(AnalyticsActions.scala:27)
	at scala.Option.flatMap(Option.scala:171)
	at widgets.analytics_v1.AnalyticsActions$.$anonfun$resolveMggTrackerConfigGeneric$3(AnalyticsActions.scala:26)
	at scala.Option.flatMap(Option.scala:171)
	at widgets.analytics_v1.AnalyticsActions$.$anonfun$resolveMggTrackerConfigGeneric$2(AnalyticsActions.scala:25)
	at scala.Option.flatMap(Option.scala:171)
	at widgets.analytics_v1.AnalyticsActions$.$anonfun$resolveMggTrackerConfigGeneric$1(AnalyticsActions.scala:24)
	at scala.Option.flatMap(Option.scala:171)
	at widgets.analytics_v1.AnalyticsActions$.resolveMggTrackerConfigGeneric(AnalyticsActions.scala:22)
	at widgets.analytics_v1.AnalyticsActions$.resolveMggTrackerConfig(AnalyticsActions.scala:39)
	at widgets.analytics_v1.Analytics_v1.$anonfun$render$1(Analytics_v1.scala:43)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:60)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I was using scala 2.12.2, 2.12.7. There is a 2.12.8 used by Scastie
build.sbt
```
resolvers += Resolver.sonatypeRepo("snapshots")

libraryDependencies ++= Seq(
  "xyz.wiedenhoeft" % "scalacrypt_2.11" % "0.5-SNAPSHOT"
)
```

**Comment by Richard-W** [comment] 2019-03-07 10:27
This is most likely because you're using a library built for Scala 2.11 with Scala 2.12. Setting the Scala version to 2.11.12 in Scastie makes it run without the exception.

That said this library is experimental and has not been properly vetted by experts. Be very careful when using it! I don't currently have time to work on this library. I will accept pull requests though.

Closing because the root-cause of the issue is a Scala version mismatch and 2.12 is just not supported yet.

**Closed by Richard-W** 2019-03-07 10:27 UTC

**Comment by Richard-W** [comment] 2019-03-07 10:37
Correction: Git master was already ported to 2.12. It's not published but you can build a scalacrypt artifact compatible with Scala 2.12 locally.

**Comment by thekia19** [comment] 2019-03-07 12:33
> Correction: Git master was already ported to 2.12. It's not published but you can build a scalacrypt artifact compatible with Scala 2.12 locally.

I tried. I didn't succeed.
And I know that it's not supported for 2.12 yet, but assumed it could be interesting for you.

**Comment by richard-w** [comment] 2019-03-07 19:03
Travis still built it successfully using openjdk 8. I had some problems locally too (sun.misc.BASE64* seems to be gone from recent openjdk versions).

I pushed a fix to master. It should work now. Also travis now builds with openjdk 10.
